---
title: "Coastal Bird Monitoring at Boston Harbor Islands NRA"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(NETNCoastalBirds)

# read in data files
species_tlu<-read.csv("./data/SppSurvey_tlu.csv")
species<-species_tlu$CommonName
surveys<-read.csv("./data/tlu_surveys.csv")

incub.yr<-read.csv("./data/incub_yr.csv")
incub.day<-read.csv("./data/incub_day.csv")
creche.yr<-read.csv("./data/creche_yr.csv")
creche.day<-read.csv("./data/incub_day.csv")
nests.yr<-read.csv("./data/nests_yr.csv")
incub_raw<-read.csv("./data/incub_raw.csv")
creche_raw<-read.csv("./data/creche_raw.csv")
nests_raw<-read.csv("./data/nests_raw.csv")
amoy_raw<-read.csv("./data/amoy_raw.csv")
```

Select species and survey type {.sidebar}
===============================
```{r}

selectInput("species", label = "Select species", 
            species, selected = "COEI")

selectInput("survey", label = "Select survey type", 
            c("Boat", "Ground"))

# radioButtons(inputId = "overlay", label = "Overlay plot",choices=c("Island = island","Species= species","life stage= var"), selected = "life stage")

```


Map
===================================== 
```{r map, echo=FALSE, warning=FALSE, comment= NA,eval = TRUE}
### import shapefile here
library(sf)
library(rgdal)
#park.bounds<-st_read("./GIS/bounds/BOHA_Boundary_2003_with_Intertidal.shp")
##surveys.sp <- st_read(".shp")

### import spatial data and handle projections
proj<-'+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'

creche.route<- readOGR("./GIS/routes",  layer = "Segment_COEI_Creche", verbose= FALSE)

incub.route<- readOGR("./GIS/routes",  layer = "Segment_Gull_DCCO_Incubation", verbose= FALSE)
incub.route<-spTransform(incub.route,proj)
waders.nest.route<- readOGR("./GIS/routes",  layer = "Segment_Waders_Nest2", verbose= FALSE)
waders.nest.route<-spTransform(waders.nest.route,proj)
gull.nest.route<- readOGR("./GIS/routes",  layer = "Segment_Gull_DCCO_Nest", verbose= FALSE)
gull.nest.route<-spTransform(gull.nest.route,proj)
tern.route<-readOGR("./GIS/routes",  layer = "Segment_Terns_All", verbose= FALSE)
tern.route<-spTransform(tern.route,proj)
amoy.route<-readOGR("./GIS/routes",  layer = "Segment_AMOY_All", verbose= FALSE)
amoy.route<-spTransform(amoy.route,proj)
coei.nest.route<- readOGR("./GIS/routes",  layer = "Segment_COEI_Nest", verbose= FALSE)
coei.nest.route<-spTransform(coei.nest.route,proj)


#setup map

library(leaflet)

renderLeaflet({
 
 

  RouteData= reactive({

  SpeciesName = reactive({
    species_tlu$Species_Code[species_tlu$CommonName %in% input$species]
  })

  SurveyType = reactive({
    species_tlu$Survey_Type[species_tlu$Survey_Class %in% input$survey & species_tlu$CommonName %in% input$species]
  })

    # select the appropriate survey data
    if(SurveyType() %in% "Creche" ){
      creche.route
    } else if(SpeciesName() %in% "COEI" & SurveyType() %in% "Nest" ){
      coei.nest.route
    } else if(SpeciesName() %in% "AMOY"){
      amoy.route
    } else if(SpeciesName() %in% c("DCCO","HERG","GBBG") & SurveyType() %in% "Incubation" ){
      incub.route
    } else if(SpeciesName() %in% c("DCCO","HERG","GBBG") & SurveyType() %in% "Nest"){
      gull.nest.route
    }else if(SpeciesName() %in% c("GLIB","SNEG","GREG","BCNH") & SurveyType() %in% "Nest"){
      waders.nest.route
    } else if(SpeciesName() %in% c("COTE","LETE")){
      tern.route
    }

  })
  
  ### set up map
 
  leaflet(data=RouteData()) %>% 
    addTiles() %>% 
    #setView(lat= 42.318027, lng= -70.938908, zoom = 12) %>% 
    addPolygons(
                weight = 1.5,
                    opacity = .9,
                    color = "white",
                    dashArray = "",
                    fillOpacity = 0.7,
                    highlight = highlightOptions(
                      weight = 5,
                      color = "#7777",
                      dashArray = "",
                      fillOpacity = 0.7,
                      bringToFront = TRUE)) %>% 
    # Base groups
    addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OSM") %>%
    addProviderTiles(providers$Esri.WorldImagery, group = "Imagery (default)") %>%
    addProviderTiles(providers$Esri.WorldTopoMap, group = "Topo") %>%
    #layers
    addLayersControl(
      baseGroups = c("Imagery (default)", "OSM", "Topo"),
      options = layersControlOptions(collapsed = FALSE),
      position = 'bottomleft') 
     
  
})
   
       
  
```

Survey History
=====================================
``` {r}

renderTable({

  SpeciesName = reactive({
    species_tlu$Species_Code[species_tlu$CommonName %in% input$species]
    
  })
  
  SurveyType = reactive({
    species_tlu$Survey_Type[species_tlu$Survey_Class %in% input$survey & species_tlu$CommonName %in% input$species]
    
  })
  
  if(SurveyType() %in% "Creche"){
    df <-creche_raw
} else if(SurveyType() %in% "Nest"){
    df <-nests_raw
} else if(SurveyType() %in% "Incubation"){
    df <-incub_raw
} else if(SpeciesName() %in% "AMOY"){
    df <-amoy_raw
}
  
  shiny::validate(
    shiny::need(nrow(df) > 0, message =  "There are no surveys for this species.")
    )
  
  tbl<-NETNCoastalBirds::GetSurveyMat(df, species= SpeciesName(), survey= SurveyType())[-c(1:3)]
      
  
  tbl
  
})
```


Plot annual counts 
=====================================

``` {r plots}

renderPlot({
  
   SpeciesName = reactive({
    species_tlu$Species_Code[species_tlu$CommonName %in% input$species]
    
  })
  
  SurveyType = reactive({
    species_tlu$Survey_Type[species_tlu$Survey_Class %in% input$survey & species_tlu$CommonName %in% input$species]
    
  })
  
  ### select summary  survey data depending on inputs
  
 # incubation surveys
 if(SpeciesName() %in% c("DCCO","GBBG", "HERG") & SurveyType() %in% "Incubation") { 
   
   surveys_sum<-incub.yr[incub.yr$Species_Code %in% SpeciesName(),]
   
   pl<-PlotBirds(surveys_sum, stat= "max", overlay = "var", legend = F, raw_count = T,plot_title = "yes")
   
   }
 
  # creche surveys
 if(SpeciesName() %in% "COEI" & SurveyType() %in% "Creche") { 
   surveys_sum<-creche.yr[creche.yr$stat %in% "max",]
   
   pl<-PlotBirds(surveys_sum, stat= "max", overlay = "var", legend = T, raw_count = T,plot_title = "yes")
   }
 
  # ground nest surveys
  if(SurveyType() %in% "Nest") { 
    surveys_sum<-nests.yr[nests.yr$Species_Code %in% SpeciesName(),]
    
    pl<-PlotBirds(surveys_sum, stat= NA, overlay = "var", legend = T, raw_count = T,plot_title = "yes")
    
    } 

  print(pl)
  
})

```

View raw survey data
=====================================

``` {r raw_tabl}
DT::renderDataTable({
  # extract survey information from ui inputs
  SpeciesName = reactive({
    species_tlu$Species_Code[species_tlu$CommonName %in% input$species]
    
  })
  SurveyType = reactive({
    species_tlu$Survey_Type[species_tlu$Survey_Class %in% input$survey & species_tlu$CommonName %in% input$species]
    
  })
 
  ### select raw survey data depending on inputs
  
 # incubation surveys
 if(SurveyType() %in% "Incubation"){
   surveys_raw<-incub_raw %>% 
     dplyr::filter(Species_Code %in% SpeciesName()) %>% 
     dplyr::select(Island,Segment, Date,`Primary Survey` = Survey_Primary, `Life stage` = Species_Unit, Count= Unit_Count, Observer)
   }
 
  # creche surveys
 if(SpeciesName() %in% "COEI" & SurveyType() %in% "Creche") { 
   surveys_raw<-creche_raw %>% 
     dplyr::select(Island,Segment, Date,`Primary Survey` = Survey_Primary,`Life stage` = Species_Unit,Count= Unit_Count, Observer)}
 
  # ground nest surveys
  if(SurveyType() %in% "Nest") { 
    surveys_raw<-nests_raw %>% 
      dplyr::filter(Species_Code %in% SpeciesName())%>% 
      dplyr::select(Island,Segment, Date,`Primary Survey` = Survey_Primary, `Nest Status` = Nest_Status, Nests= Unit_Count, Eggs = Egg_Count, Chicks = Chick_Count, Observer)
  
  } 

   if(nrow(surveys_raw) == 0){print("Data are not collected for that species and survey combination.")}else{
   DT::datatable(surveys_raw,caption = 'Raw survey data', filter = list(position = "top", clear = T, plain= T),fillContainer =T,options = list(pageLength = 10, autoWidth = TRUE))
   }
  
})

```

View summary data
=====================================

``` {r tables}
library(magrittr)
DT::renderDataTable({
  
  SpeciesName = reactive({
    species_tlu$Species_Code[species_tlu$CommonName %in% input$species]
    
  })
  
  SurveyType = reactive({
    species_tlu$Survey_Type[species_tlu$Survey_Class %in% input$survey & species_tlu$CommonName %in% input$species]
    
  })
  
   ### select raw survey data depending on inputs
 # incubation surveys
 if(SpeciesName() %in% c("DCCO","GBBG", "HERG") & SurveyType() %in% "Incubation") { 
   surveys_sum<-
     dplyr::filter(incub.yr, Species_Code %in% SpeciesName() & stat %in% "mean") %>% 
     dplyr::select(Island,time,`Raw count`= value,Density = valuePerSurveySize, `Survey Units`= Survey_Units)
   
   }
 
  # creche surveys
 if(SpeciesName() %in% "COEI" & SurveyType() %in% "Creche") { 
   surveys_sum<-
     dplyr::filter(creche.yr, stat %in% "max") %>% 
     dplyr::select(Island,time,`Life stage`= variable,`Raw count`= value,Density = valuePerSurveySize, `Survey Units`= Survey_Units)
  }
 
  # ground nest surveys
  if(SurveyType() %in% "Nest") { 
    surveys_sum<-dplyr::filter(nests.yr, Species_Code %in% SpeciesName()) %>% 
    dplyr::select(Island,time,`Life stage`= variable,`Raw count`= value,Density = valuePerSurveySize, `Survey Units`= Survey_Units)
  }
    
  if(nrow(surveys_sum) == 0){"Data are not collected for that species and survey combination."}else{ 
    
  DT::datatable(surveys_sum,caption = 'Summary survey data', filter = list(position = "top", clear = T, plain= T),fillContainer =T,options = list(pageLength = 10, autoWidth = F))
  }
  
})


```
